const DATA = {
  "Heavy Drinker": "술꾼",
  "Roaming Isle": "떠도는 섬",
  "Cyber-Sai": "사이버 쌍차",
  "Bread Knife": "빵칼",
  "Handaxe": "손도끼",
  "Zookeeper": "조련사",
  "Friendzone": "친구 사이",
  "Star Chart": "별자리 지도",
  "Dragon Tooth": "드래곤의 이빨",
  "Training Dummy": "훈련용 더미",
  "Buster": "폭파자",
  "Spare Change": "잔돈",
  "Abacus": "주판",
  "Aggressive": "공격적",
  "Brewmaster": "양조의 달인",
  "Gain Strength": "근력 얻기",
  "Relic Training": "유물 훈련",
  "Work as Protection": "보호한다",
  "Business Card": "명함",
  "The Core": "핵심코어",
  "Small Gains": "작은 것의 힘",
  "Molten Ball Blaster": "용암구 발사기",
  "Pip": "핍",
  "Machine Learning": "기계학습",
  "Bladed Hoverboard": "칼날 호버보드",
  "Toaster": "토스터",
  "Pole Position": "선두로 출발",
  "Diana-Saur": "다이아나사우루스",
  "Essence Overflow": "넘치는 정수",
  "Premium Yellow Piggles": "고급형 노랑 피글스",
  "Vitality Boost": "활력 증강",
  "Dirty Dishes": "더러운 식기",
  "Assault Protocol": "공격 프로토콜",
  "Void Rage": "공허의 분노",
  "Freefall Simulator": "자유낙하 시뮬레이터",
  "B1&B2": "B1&B2",
  "C4": "C4",
  "Righty Tighty": "오른쪽으로 조이기",
  "Kitchen Scale": "주방 저울",
  "Play Hide and Seek": "숨바꼭질한다",
  "Shadowed Cloak": "그림자 망토",
  "Improvised Protection": "임시 보호막",
  "Gunner": "총잡이",
  "Colt": "콜트",
  "Terrorform": "테러폼",
  "Brawler": "싸움꾼",
  "Chemsnail": "화학달팽이",
  "Hydra Rewards": "히드라 보상",
  "Dino Disguise": "공룡 변장",
  "Slowed Targets": "느려진 사냥감",
  "Dooley's Crib": "둘리의 집",
  "Angle Grinder Drone": "회전 날 드론",
  "Landlord": "지주",
  "Gulch's Dive": "걸치의 다이브",
  "Instant Noodles": "컵라면",
  "Tinker": "팅커",
  "Extract": "추출물",
  "Tiny Dancer": "작은 춤꾼",
  "Lich": "리치",
  "Appetizer": "전채 요리",
  "Brew a Potion": "물약을 양조한다",
  "Candy Stash": "사탕 보관함",
  "Precision Tools": "정밀 도구",
  "Generous Tip": "후한 팁",
  "Proceed to the Vault": "금고로 진입한다",
  "Murkwood Bayou": "머크우드 늪지",
  "Elixir of Immortality": "불사의 비약",
  "Deadly Eye": "치명적인 조준",
  "Snack Time": "간식 시간",
  "3rd Quarter": "3쿼터",
  "Pyrocarbon": "열분해 탄소",
  "Guardian's Gorge": "수호자의 협곡",
  "Pygmalien": "피그말리엔",
  "Green Piggles R": "초록 피글스 R",
  "Forja": "포르자",
  "Bolas": "투척구",
  "Crashing Waves": "부서지는 파도",
  "Coin Collector": "동전 수집가",
  "Optical Augment": "광학 증강기",
  "Trash Titan": "쓰레기 거인",
  "Vehicle Training": "탈것 훈련",
  "Coconut Crab": "코코넛 크랩",
  "Railgun": "레일건",
  "Gastro": "가스트로",
  "Cauldron": "가마솥",
  "Hot Springs": "온천",
  "[DEBUG] Enchant": "텍스트 누락",
  "Katana": "카타나",
  "Jetpack": "제트팩",
  "Kusarigama": "사슬낫",
  "Hologram Projector": "홀로그램 프로젝터",
  "Preening Duelist Rewards": "자만한 결투사 보상",
  "Optimization Protocol": "최적화 프로토콜",
  "Overclock": "오버클럭",
  "Ice Luge": "얼음 주로",
  "Potion Rack": "물약 선반",
  "Social Training": "사교 훈련",
  "Hunker Down": "웅크리기",
  "Tethers": "고정줄",
  "Everlasting Life": "영원한 생명",
  " Wish for Immortality": "불멸을 소망한다",
  "Bouncertron": "문지기 로봇",
  "Fishing Rod": "낚싯대",
  "Bloodreef Raider": "블러드리프 습격자",
  "Toxicity": "독성",
  "Jay Jay": "제이 제이",
  "Swash Buckle": "화려한 버클",
  "Best Friend": "최고의 친구",
  "Joyful Jack": "즐거운 잭",
  "Reagent Harvesting": "시약 수확",
  "Property Baron": "자산 거물",
  "Flamethrower": "화염방사기",
  "Barrier Protocol": "방어 프로토콜",
  "Balloon Engine": "열기구 엔진",
  "Proteus": "프로테우스",
  "Party Like it's 011111001111": "011111001111년처럼 파티하자",
  "Dive Weights": "잠수용 추",
  "Blowguns Trap": "블로우건 함정",
  "Stopwatch": "스톱워치",
  "Boar Market": "멧돼지 상점",
  "Weapon Training": "무기 훈련",
  "Whale Steak": "고래 스테이크",
  "Supply Drop": "보급 투하",
  "Double Down": "승부수",
  "Power Up": "파워 업",
  "Windmill": "풍차",
  "3D Printer": "3D 프린터",
  "Biomerge Arm": "생체융합 팔",
  "Security Camera": "보안 카메라",
  "Induction Aegis": "유도 방패",
  "Viper": "독사",
  "Old Zane": "노련한 제인",
  "Spiky Shield": "가시박힌 방패",
  "Charging Station": "충전소",
  "Professor Riggle": "리글 교수",
  "Sabretooth": "검치호랑이",
  "Floor Spike": "바닥 가시",
  "Model Ship": "모형 배",
  "Foreman": "작업반장",
  "Sponsorship": "후원",
  "Toxic Spoils": "유독성 전리품",
  "Heal Training": "회복 훈련",
  "Quick Ignition": "빠른 점화",
  "Excellent Vintage": "최고급 빈티지",
  "Paralyzing Rush": "마비 돌진",
  "Quicken Weapons": "빨라진 무기",
  "Gunpowder": "화약",
  "Guard Locker": "경비 사물함",
  "Join the Cult": "광신도 집단에 가입한다",
  "[DEBUG] Start of Fight Transform": "텍스트 누락",
  "Kite": "연",
  "Sifting Pan": "체질용 팬",
  "Ethergy Conduit": "에테르 에너지 도관",
  "Stelle's Workshop": "스텔의 작업실",
  "Ryukon": "류콘",
  "Concentrated Venom": "농축된 독",
  "Card Table": "카드 테이블",
  "Billboard": "광고판",
  "Nesting Doll": "마트료시카",
  "Seminar": "강연",
  "Backroom Dealings": "암거래",
  "Void Shield": "공허의 방패",
  "Study": "공부",
  "Darkstone Focuser": "암석 집중기",
  "Endurance": "지구력",
  "Treasure Chest": "보물 상자",
  "Pickpocket": "소매치기",
  "Hot Spot": "열점",
  "Iron Sharpens Iron": "쇠로 쇠 벼리기",
  "Piano": "피아노",
  "Inexorable": "냉혹함",
  "DJ Circuit Breaker": "DJ 서킷 브레이커",
  "New Coating": "새 도포제를 바른다",
  "Industrialist": "산업가",
  "Appraisal": "감정",
  "Dragon Whelp": "어린 드래곤",
  "Adira": "아디라",
  "Bellelista": "벨 리스타",
  "Magic Carpet": "마법 양탄자",
  "Seashadow": "바다의그림자",
  "Security Center": "보안 센터",
  "Regular Maintenance": "정기 정비",
  "Coupon": "쿠폰",
  "Exploit": "악용한다",
  "Food Training": "음식 훈련",
  "[DEBUG] Gland": "텍스트 누락",
  "Cauterizing Blade": "소작의 칼날",
  "Lens": "렌즈",
  "Walter Cooler": "정숙이",
  "Cult Member": "광신도",
  "Holo-Disguise Generator": "홀로 위장 생성기",
  "Cobweb": "코브웹",
  "Work as Navigator": "항해사로 일한다",
  "Quality over Quantity": "양보다 질",
  "Nanobot Construction": "나노봇 건설",
  "Wink": "윙크",
  "Ammo Cache": "탄약 저장고",
  "Boomerang": "부메랑",
  "Soul Ring": "영혼 반지",
  "Show Globe": "전시용 구슬",
  "Load Up": "장전",
  "Mentor's Guidance": "멘토의 지도",
  "Defensive Drills": "방어 집중 훈련",
  "Necronomicon": "네크로노미콘",
  "Get Bronze item": "브론즈 아이템 획득",
  "Cache of Riches": "재물 은닉처",
  "Watch Your Step!": "발밑을 조심해!",
  "Black Rose": "검은 장미",
  "Balanced Workout": "균형 잡힌 운동",
  "Swole": "근육질",
  "Piggles Protectors": "피글스 보관함",
  "Install Defense System": "방어 시스템을 설치한다",
  "Qomatz": "코마츠",
  "Get Sharpening Stone": "숫돌을 얻습니다",
  "Pig Out": "폭식하기",
  "Toxic Spores": "유독성 포자",
  "Invest in Yourself": "나에게 투자하기",
  "Infinite Potion": "무한의 물약",
  "Siphoned Shield": "흡수 방패",
  "Glass Cannon": "유리 대포",
  "Frost Street Challenger": "서릿길 도전자",
  "Warm Hugs": "따뜻한 포옹",
  "Ritual of Defiance": "반항의 의식",
  "Steam Hose": "증기 호스",
  "Hyper Focus": "초집중",
  "Retaliatory Toxins": "반격용 독소",
  "Re-Tooled": "재정비",
  "Food Coma": "식곤증",
  "Quill and Ink": "깃펜과 잉크",
  "Biohazard": "생물학적 위험",
  "Critical Core": "치명타 코어",
  "Lifting": "웨이트 훈련",
  "Magma Core": "마그마 핵",
  "Watch": "시계",
  "Legendary-tier Merchant": "전설 등급 상인",
  "Cash Out": "현금 인출",
  "Right Eye": "오른쪽 눈",
  "Sapphire": "사파이어",
  "Magician's Top Hat": "마술사의 실크햇",
  "Butter": "버터",
  "Letting off Steam": "과부하 해소",
  "Choose Wealth": "부를 고른다",
  "Race Carl": "레이스 칼",
  "Run": "여정",
  "Blueberry Pie": "블루베리 파이",
  "Gland": "분비샘",
  "Cash Register": "계산대",
  "Saffron": "사프란",
  "Strong Brew": "진한 묘약",
  "Dooley's Scarf": "둘리의 스카프",
  "Hypergreens": "하이퍼그린",
  "First Degree Burns": "1도 화상",
  "Frost Totem": "서리 토템",
  "Celestial Conduit": "천상의 통로",
  "Desperate Strike": "필사적인 타격",
  "Improvised Poison": "임시 독약",
  "Forklift": "지게차",
  "[DEBUG] Arbitrage": "텍스트 누락",
  "Pile of Gold": "골드 더미",
  "Buddy System": "동료 체계",
  "Get an Expedition Ticket": "탐험 티켓을 얻습니다",
  "Scramble Fighters": "요격 전투기",
  "Unwavering": "굳셈",
  "Eternal Torch": "영원의 횃불",
  "Bag of Gold": "금 주머니",
  "Wild Quillback": "야생 등가시",
  "Piggy Bank": "돼지 저금통",
  "Yellow Piggles A": "노랑 피글스 A",
  "Tempest Bravo": "템페스트 칼잡이",
  "Aimbot": "에임봇",
  "Yellow Piggles L": "노랑 피글스 L",
  "Black Pepper": "흑후추",
  "Overclocked": "한계 돌파",
  "Dungeon move forward 2": "Dungeon move forward 2",
  "Personal Trainer": "개인 트레이너",
  "Hardly Workin'": "놀고 먹기",
  "Mr. Richardson": "리처드슨 씨",
  "Trickle Down Economics": "낙수 효과",
  "Apprentice Flamewright": "견습 화염술사",
  "Healthy Hoarder": "건강한 수집가",
  "Car Conductor": "차량 지휘자",
  "You feel faster": "더 빨라진 느낌입니다",
  "Dual Wield": "이도류",
  "Annex Trooper": "애넥스 병사",
  "Badblocker": "배드블로커",
  "Burning Caldera": "불타는 분화구",
  "Hoverbike Hooligan": "호버바이크 폭주족",
  "Blizzard": "눈보라",
  "Dodge Taxes": "탈세한다",
  "Jules": "줄스",
  "Toxic Flame": "유독성 불",
  "Secret Formula": "비밀 공식",
  "Ring King Gauntlets": "격투기 왕 건틀릿",
  "Barbed Claws": "가시 발톱",
  "Weaselpede": "지네족제비",
  "Mod Squad": "모드 분대",
  "Gearnola Bar": "기어놀라 바",
  "Insect Wing": "곤충 날개",
  "House Party": "홈파티",
  "Stunning Strike": "기절시키는 타격",
  "Go Fishing": "낚시하기",
  "Keychain": "열쇠고리",
  "Escort the Convoy": "호송대를 호위합니다",
  "Venomous Blade": "독성 칼날",
  "Kev's Armory": "케브의 무기고",
  "Infernal Frigate": "인페르날 호위함",
  "Ice Pick": "얼음 송곳",
  "Boss Harrow": "하로우 대장",
  "Morning Rush": "아침 출근길",
  "Creeping Toxins": "스며드는 독소",
  "Temporary Shelter": "임시 대피소",
  "Langxian": "랑시엔",
  "Cosmic Amulet": "우주 부적",
  "Get a Gumball": "사탕껌을 뽑는다",
  "Mixed Message": "소통 오류",
  "Heavy Shielding": "무거운 보호막",
  "Sabotage": "사보타주",
  "Premium Orange Piggles": "고급형 주황 피글스",
  "Holsters": "권총집",
  "Apprentice Weaponsmith": "견습 무기 대장장이",
  "Ventriloquist": "복화술사",
  "Tall Buildings": "고층 건물",
  "Pepper Spray": "후추 스프레이",
  "Pilot's Wings": "조종사의 날개",
  "Void Knight": "공허의 기사",
  "Junkyard Club": "고물장 곤봉",
  "Pancakes": "팬케이크",
  "Flashbang": "섬광탄",
  "Vanessa": "바네사",
  "Pearl": "진주",
  "28 Hour Fitness": "28시간 헬스장",
  "Banehand": "독술사",
  "Closed Sign": "휴업 간판",
  "Gumball Machine": "사탕껌 자판기",
  "Rust": "녹",
  "MagShield": "자력보호막",
  "Junk Food": "정크 푸드",
  "Neural Toxin": "신경독",
  "Kina": "키나",
  "Juggler": "저글러",
  "Farm to Table": "농장에서 식탁까지",
  "Golf Clubs": "골프채",
  "Dragon Heart": "드래곤의 심장",
  "Zara": "자라",
  "Companion Core": "동료 코어",
  "Flashy Mechanic": "화려한 정비공",
  "Pickled Peppers": "절임 고추",
  "Seafood Cracker": "해산물 크래커",
  "Deadly Duel": "치명적인 결투",
  "Invulnerability Potion": "무적 물약",
  "Tommoo Gun": "토무 건",
  "Z-Shield": "Z-실드",
  "Self Promotion": "자신을 홍보한다",
  "Crook": "지팡이",
  "Chum": "미끼",
  "Lightbulb": "전구",
  "The Docks": "부두",
  "Extended Magazine": "탄창을 확장한다",
  "Void Energy": "공허의 에너지",
  "Sushi Boat": "초밥 보트",
  "Wish for Wealth": "부를 소망한다",
  "Lethargy": "무기력",
  "Infernal Dreadnought": "인페르날 드레드노트",
  "Flamberge": "플랑베르주",
  "Test Fire": "발사를 시험한다",
  "Tatiana": "타티아나",
  "Launch Tower": "발사탑",
  "Chimeric Egg": "키메라 알",
  "Mystery Bundle": "랜덤 박스",
  "Fate's Bounty": "운명의 현상금",
  "Pet Rock": "애완돌",
  "Icewatch Warden": "얼음감시 수호자",
  "Powder Keg": "화약통",
  "Upgrade an item": "아이템을 강화합니다",
  "Pyromania": "방화광",
  "Coral Armor": "산호 갑옷",
  "Scrap Salvage": "고철 수집",
  "Spiked Buckler": "소형 가시 방패",
  "Temper": "연마한다",
  "Pillbuggy": "필버기",
  "SkillCard - Speed": "SkillCard - Speed",
  "Stocked": "비축",
  "Fortis": "포티스",
  "Intrusion Countermeasures": "침입 대응책",
  "Gold-tier Garnish": "골드 등급 가니시",
  "Admiral's Badge": "제독의 배지",
  "Improvised Bludgeon": "임시 둔기",
  "Obsidian Covenant": "흑요석 계약",
  "Transfiguration": "변형",
  "Gain 7 Gold": "7 골드를 얻습니다",
  "Chopsticks": "젓가락",
  "Figurehead": "선수상",
  "Battery": "배터리",
  "Flagship": "기함",
  "Scavenger Hunt": "보물찾기",
  "Gravity's Altar": "중력의 제단",
  "Reinforced Steel": "강화 강철",
  "Bunker": "벙커",
  "Launcher Core": "발사기 코어",
  "Appreciated Value": "가치 상승",
  "[SKILL TEMPLATE]": "[SKILL TEMPLATE]",
  "Burning Shield": "불타는 방패",
  "Anything to Win": "승리를 위해선 무엇이든",
  "Prince Marianas": "마리아나스 왕자",
  "Handyman": "만능 기술자",
  "Nanobot Orange": "나노봇 오렌지",
  "Boilerroom Brawler": "보일러실 싸움꾼",
  "Rewards Card": "포인트 카드",
  "Fishing Net": "어망",
  "Mag Storage": "탄창 보관함",
  "Secret Ingredient": "비밀 재료",
  "Jambalaya": "잠발라야",
  "Large Investment": "대규모 투자",
  "Cymon": "사이먼",
  "Find a Friend": "친구를 찾는다",
  "Propeller": "프로펠러",
  "Shield Training": "방어 훈련",
  "YLW-M4NT1S": "황-4ㅁr커",
  "Eject, Eject!": "탈출, 탈출!",
  "Sanguine Valley": "붉은 협곡",
  "Upgrade": "강화",
  "Search for Abandoned Tools": "버려진 도구를 찾아본다",
  "Salamander Pup": "새끼 샐러맨더",
  "Thanks": "고마워",
  "Steam Ladle": "증기 국자",
  "Rit": "릿",
  "Magic Mirror": "마법 거울",
  "Laboratory": "연구소",
  "Grappling Hook": "갈고리",
  "Rush": "돌격",
  "Apparel Training": "의류 훈련",
  "Artificial Heart": "인공 심장",
  "Skyspirit Ashes": "하늘정령의 재",
  "Awakened District": "깨어난 구역",
  "Sleeping Potion": "수면 물약",
  "Flanking Shield": "측면 방패",
  "Frost Potion": "냉기 물약",
  "Dart Launcher": "다트 발사기",
  "Feed It": "먹이를 준다",
  "Barkun": "바쿤",
  "The Artist": "예술가",
  "Skyscraper": "마천루",
  "Elite Duelist": "정예 결투사",
  "Cheese Wheel": "치즈 덩어리",
  "[DEBUG] Give Tag Test item": "텍스트 누락",
  "Runic Potion": "룬 물약",
  "Transform Reagents": "시약 변환",
  "Hover Tech": "부양 기술",
  "Into the Void": "공허 속으로",
  "Sat-Comm": "위성 통신기",
  "Decanter": "디캔터",
  "Obstacle Course": "장애물 코스",
  "Frontline Logistics": "최전방 보급",
  "Raid the Vault": "금고를 습격한다",
  "Likit": "리키트",
  "Emergency Draught": "응급 영약",
  "Duct Tape": "덕트 테이프",
  "Barnacle Crusted": "따개비 투성이",
  "Chocoholic": "초콜릿 중독자",
  "Dessert": "디저트",
  "Panic": "공황",
  "Seeing Stars!": "별이 보인다!",
  "Sirens": "사이렌",
  "Meat Tenderizer": "고기 망치",
  "Chilling Touch": "차가운 손길",
  "Claws": "발톱",
  "Delayed Burn": "지연된 불꽃",
  "Orlin": "올린",
  "Weakpoint Detector": "약점 탐지기",
  "Setup Tourist Attraction": "관광 명소를 설치한다",
  "Bomb Squad": "폭탄 처리반",
  "Ifrit": "이프리트",
  "Delivery Drone": "배송 드론",
  "Epic Battle": "장엄한 전투",
  "Cookbook": "요리책",
  "Shipment": "배송물",
  "Yum!": "맛있어!",
  "Hospital": "병원",
  "Gain 10 Speed": "속도 10 획득",
  "Tempering": "단련",
  "Free Samples": "무료 견본",
  "Torpedo": "어뢰",
  "Coffee": "커피",
  "Ship [OnBuy] effectdata 2": "Ship [OnBuy] effectdata 2",
  "Sponsored Apparel": "후원복",
  "Gorgon Noble": "귀족 고르곤",
  "Fort": "요새",
  "Octopus": "문어",
  "Calico": "삼색 고양이",
  "Genie Lamp": "지니 램프",
  "Crit Training": "치명타 훈련",
  "Globe": "지구본",
  "Power Sander": "전동 연마기",
  "Ruby": "루비",
  "Ni-Kola": "니-콜라",
  "Praeteria": "프레테리아",
  "Venom": "맹독",
  "Throwing Knives": "투척 나이프",
  "Seraphim": "세라핌",
  "Ravenous": "굶주림",
  "Pile of Gold 7": "골드 더미 7",
  "Jitte": "짓테",
  "Small Investment Payout": "소규모 투자 지급",
  "Snowmobile": "스노우모빌",
  "The Eclipse": "이클립스",
  "Blue Piggles L": "파랑 피글스 L",
  "Conflagration": "대화재",
  "Eating Contest": "많이 먹기 대회",
  "Bottled Explosion": "병에 담은 폭발",
  "Outmaneuver": "압도적인 기동력",
  "Flying Potion": "비행 물약",
  "Cult Member Special": "광신도 스페셜",
  "Flanking Criticals": "측면 치명타",
  "Gain 6 Gold": "6 골드를 얻습니다",
  "Cake Batter": "케이크 반죽",
  "Death Caps": "맹독 버섯",
  "Acid Sprayer": "산 분사기",
  "Robotic Factory": "로봇 공장",
  "Yetarian Tomb": "예타리아 무덤",
  "Sirocco Steppe": "시로코 초원",
  "Toolbox": "도구상자",
  "Old Saltclaw": "노련한 소금집게",
  "Firecrackers": "폭죽",
  "Truffles": "트러플",
  "Harpoon": "작살",
  "Get 5 Gumballs": "사탕껌을 5개 뽑는다",
  "Covetous Thief": "탐욕스러운 도둑",
  "Slohmor Lumbra": "슬로모르 룸브라",
  "Mak's Laboratory": "막의 연구소",
  "Crude Tools": "조잡한 도구",
  "Lifting Gloves": "역도 장갑",
  "Solar Drone": "태양광 드론",
  "Luxury Kiuas": "고급 난로",
  "Vital Sacrifice": "생명을 희생한다",
  "Cosmic Roc": "우주의 로크",
  "Workin' Hard": "열심히 일하기",
  "Void Render": "공허의 형상",
  "Haddy's Hat Reward": "해디의 모자 보상",
  "Arbalest": "석궁",
  "Rapid Relief": "신속한 회복",
  "Flame Juggler": "화염 곡예사",
  "Spatula": "주걱",
  "Enchant": "마법 부여",
  "Treasure Turtle": "보물 거북이",
  "Signet Ring": "인장 반지",
  "Red Piggles A": "빨강 피글스 A",
  "Junkyard Repairbot": "고물장 수리 로봇",
  "Venomander": "독도마뱀",
  "Colossal Popsicle": "거대한 빙과",
  "Spawning Test": "생성 테스트",
  "Golden Bonds": "금빛 결속",
  "Blender": "믹서기",
  "Energy Potion": "에너지 물약",
  "Tool Up": "도구 준비",
  "Choose Knowledge": "지식을 고른다",
  "Firestorm Protocol": "화염폭풍 프로토콜",
  "Potion Distillery": "물약 증류소",
  "Invest in the Convoy": "호송대에 투자",
  "On the Prowl": "사냥 중",
  "Fanged Inglet": "송곳니 잉글릿",
  "Calming Heals": "진정 회복",
  "Sharp Corners": "날카로운 모서리",
  "Dooley": "둘리",
  "Mech-Moles": "기계 두더지",
  "Open House": "오픈 하우스",
  "CPU Throttling": "CPU 성능 제한",
  "Dragonmelon": "드래곤멜론",
  "Bold Under Pressure": "위기 속 침착함",
  "Air-Pressure Rifle": "공기압 소총",
  "Prospero": "프로스페로",
  "Dungeon chest": "던전 상자",
  "Juicy Gossip": "흥미진진한 소문",
  "Caltrops Trap": "마름쇠 함정",
  "Tok's Clocks": "톡의 시계",
  "Free Session": "무료 세션",
  "Get Diamond item": "다이아몬드 아이템을 얻습니다",
  "Bushel": "바구니",
  "Get Silver item": "실버 등급 아이템 획득",
  "Adaptive Ordinance": "적응성 폭발물",
  "Accept the Deal": "제안을 수락한다",
  "Fire Claw": "화염 발톱",
  "Bullet Time": "슬로우 모션",
  "Line Cook": "주방 보조",
  "Escalation Protocol": "점증적 프로토콜",
  "Cinder Chase": "불씨 찾기",
  "Run a Race": "경주하기",
  "Hourglass": "모래시계",
  "RED-F1R3FLY": "적-반D불2",
  "Mountain Pass": "산길",
  "Malafang": "말라팡",
  "Hangar": "격납고",
  "Dooltron Mainframe": "둘트론 중앙 제어실",
  "Cloud Wisp": "구름의 정령",
  "Speedrunner": "스피드러너",
  "Jabalian Drum": "자발리 드럼",
  "Durian": "두리안",
  "[DEBUG] Self Flying": "텍스트 누락",
  "Exposing Toxins": "독소 노출",
  "Basic Chocolate Bars": "기본 초코바",
  "Pelt": "동물 가죽",
  "Wake-Up Call": "깨어나는 공포",
  "D'flek": "디플렉",
  "Haunting Flight": "섬뜩한 비행",
  "Pacifist": "평화주의자",
  "Pyro Gauntlet": "화염 건틀릿",
  "Mmmm!": "음!",
  "Immolating Spark": "타오르는 불꽃",
  "Flashy Reload": "화려한 재장전",
  "Invigorating Cold": "상쾌한 추위",
  "Product Showcase": "제품 소개",
  "Get Gold item": "골드 등급 아이템을 얻습니다",
  "Argenta": "아젠타",
  "Bird Cage": "새장",
  "Cooking Mallet": "요리용 망치",
  "Boarrior": "멧돼지전사",
  "Pearl's Dig Site": "펄의 발굴지",
  "ATM": "ATM",
  "Quick Fix": "빠른 수리",
  "Trophy Hunt": "전리품 사냥",
  "Vermir": "베르미르",
  "Squirrel Suit": "다람쥐 수트",
  "Alpha Ray": "알파 레이",
  "Kyver Commander": "카이버 지휘관",
  "Showcase": "진열장",
  "Look for Spare Change": "잔돈 찾기",
  "Tiny Cutlass": "작은 커틀러스",
  "Buy it": "사기",
  "Truffleholic": "트러플중독",
  "Burst of Flame": "화염 폭발",
  "Bottled Lightning": "병에 담은 번개",
  "Hot Box": "뜨거운 상자",
  "BeFriend": "친구되기",
  "Trashtown Mayor": "쓰레기촌 시장",
  "Gingerbread Man": "진저브레드 맨",
  "Herma": "헤르마",
  "Green Gumball": "초록 사탕껌",
  "Burning Rage": "타오르는 분노",
  "Flamecoil Gem": "불꽃나선 보석",
  "Windbreaker": "바람막이",
  "Venomous Dose": "독약",
  "Tantius Carrier": "탄티우스 항공모함",
  "Oblivion Core": "망각 코어",
  "Property Training": "자산 훈련",
  "Candy Mail": "사탕 갑옷",
  "Meditation": "명상",
  "SMG": "SMG",
  "Loupe": "확대경",
  "Initial Dose": "첫 투여",
  "Healthy Friendship": "건강한 우정",
  "Oasis Guardian": "오아시스 수호자",
  "Epsilon Ray": "엡실론 레이",
  "Cargo Shorts": "카고 반바지",
  "Temple Vault": "사원 금고",
  "Botul": "보툴",
  "Wax and Wane": "위상 변화",
  "Dinosaur Training": "공룡 훈련",
  "Pinwheel": "바람개비",
  "Experimental Chef": "실험적인 요리사",
  "Nufu": "누푸",
  "Upgrade Silver": "실버 등급 강화",
  "Money Tree": "돈나무",
  "Chocolate Connoisseur": "초콜릿 미식가",
  "Find Better Craftsman": "더 실력이 좋은 장인을 찾는다",
  "Tool Training": "도구 훈련",
  "Surrounded by Joy": "기쁨에 둘러싸이다",
  "Reaching the Summit": "정상 도달",
  "Recycling Bin": "재활용 쓰레기통",
  "Like Clockwork": "시계바늘처럼",
  "Agility Boots": "민첩 부츠",
  "Thug": "불량배",
  "Second Wind": "재기",
  "Nitro": "니트로",
  "Tourist Chariot": "관광 전차",
  "Concentrated Defense": "집중 방어",
  "Fiery": "맹렬함",
  "Marbles": "구슬",
  "Submarine": "잠수함",
  "Icebreaker": "쇄빙기",
  "Flare Gun": "신호총",
  "Pile of Gold 5": "골드 더미 5",
  "Infernal Greatsword": "인페르날 대검",
  "Backup Defenses": "예비 방어",
  "Cloche Hat": "클로슈 모자",
  "Hammer": "망치",
  "Awakened Primordial": "깨어난 원시의 존재",
  "Work as Maintenance": "정비사로 일한다",
  "Get Diamond Loot": "다이아몬드 등급 전리품 획득",
  "Dr. Vortex": "볼텍스 박사",
  "Reel 'Em In": "끌어올리기",
  "Musket": "머스킷",
  "Pastry Cart": "제과 카트",
  "Shiny!": "반짝반짝!",
  "Magnifying Glass": "돋보기",
  "Chunk of Lead": "납 덩어리",
  "Incendiary Rounds": "소이탄",
  "Cinders": "불씨",
  "No Pain No Gain": "고생 끝에 낙이 온다",
  "Finn's Big Bite": "핀의 큰 한 입",
  "Barbed Wire": "철조망",
  "Old Sword": "낡은 검",
  "Maitoan Altar": "마이토안 제단",
  "[DEBUG] Peacewrought": "텍스트 누락",
  "Lord of the Wastes": "황무지의 군주",
  "Box Cutter": "커터 칼",
  "Guardian Shell": "수호의 패각",
  "Second Degree Burns": "2도 화상",
  "Cloudtop Officer": "클라우드톱 장교",
  "Nanobot": "나노봇",
  "Reconfigure": "재설정",
  "Red Envelope": "빨간 봉투",
  "Slushee": "슬러시",
  "Cool LEDs": "멋진 LED",
  "Potion Potion": "물약 물약",
  "Speed": "속도",
  "Living Flame": "살아있는 화염",
  "Purrr": "그르릉",
  "Gain 9 Gold": "9 골드를 얻습니다",
  "Bandages": "붕대",
  "Healthy Food": "건강한 음식",
  "Pendulum": "진자",
  "Heavy Machinery": "중장비",
  "Balloon Bot": "풍선 로봇",
  "Relax Bro": "진정해 친구",
  "Dire Inglet": "무시무시한 잉글릿",
  "First Aiden": "구급 에이든",
  "Tech Salvage": "테크 회수품",
  "Ice Bullets": "얼음 총알",
  "Weather Glass": "기상 유리병",
  "Oil Lantern": "유등",
  "Sell It": "판매한다",
  "Hemlock": "독미나리",
  "Gamma Ray": "감마 레이",
  "Firmware Upgrade": "펌웨어를 업그레이드한다",
  "Red Lantern": "빨간 랜턴",
  "Cookies": "쿠키",
  "Firepower": "화력",
  "Airplane Glue": "비행기 접착제",
  "Expert Pilot": "전문 조종사",
  "Terry-Dactyl": "테리 닥틸",
  "Pistol Sword": "권총검",
  "Power Drill": "전동 드릴",
  "Bread": "빵",
  "Blue Gumball": "파란 사탕껌",
  "Open Sign": "영업 표지판",
  "Virulent Research": "맹독 연구",
  "Hammlet": "햄릿",
  "Form": "폼",
  "Healthy Living": "건강한 삶",
  "Large Appetites": "왕성한 식욕",
  "Moth to a Flame": "불에 달려드는 나방",
  "Void Colossus": "공허의 거신",
  "Fiery Door": "불타는 문",
  "The Boulder": "거대한 바위",
  "Dabora": "다보라",
  "Fast Food": "패스트푸드",
  "Midsworth": "미드스워스",
  "Concentrated Firepower": "집중된 화력",
  "Begone!": "사라져라!",
  "Get Bronze Loot": "브론즈 전리품 획득",
  "Premium Piggles": "고급형 피글스 세트",
  "Block Party": "블록 파티",
  "Rocket Boots": "로켓 부츠",
  "Rainbow Potion": "무지개 물약",
  "Flamedancer": "화염춤꾼",
  "Private Runabout": "개인용 보트",
  "Gibbus": "기버스",
  "Leeches": "거머리",
  "Yellow Piggles R": "노랑 피글스 R",
  "Coral": "산호",
  "Scrap Metal": "금속 조각",
  "Eggs": "달걀",
  "Library": "도서관",
  "Weaponcraft": "무기 제작",
  "Strength Potion": "힘 물약",
  "Assembly Line": "조립 라인",
  "Large Package": "큰 패키지",
  "Force Amplifier": "힘 증폭기",
  "Fire Potion": "화염 물약",
  "Reward": "보상",
  "Icicle": "고드름",
  "[DEBUG] Repeatable Quest": "텍스트 누락",
  "Noisy Cricket": "시끄러운 귀뚜라미",
  "Hypnotic Drain": "최면을 거는 흡수",
  "Strawberries": "딸기",
  "Advanced Training": "고급 훈련",
  "Hands of Time": "시간 조율자",
  "Nanobot Red": "나노봇 레드",
  "Laurel's Favorite": "로렐의 애용품",
  "Oinkment": "꿀꿀연고",
  "Reserve Shield": "예비 방패",
  "Cannonball": "대포알",
  "Utility Box": "다용도 상자",
  "Combat Core": "전투 코어",
  "Preening Duelist": "자만한 결투사",
  "Hide": "숨기",
  "Myrrh": "몰약",
  "Crystal Bonsai": "수정 분재",
  "Healthy Heart": "건강한 심장",
  "Copper Ed": "구리 살무사 에드",
  "Dog": "개",
  "Upgrade Bronze": "브론즈 등급 강화",
  "Sniper Rifle": "저격 소총",
  "Track": "트랙",
  "Transform": "변환",
  "Open It": "연다",
  "Goop Flail": "끈끈이 도리깨",
  "Rocket Launcher": "로켓 발사기",
  "Shieldcraft": "방패제작",
  "Pantry": "식료품 저장실",
  "Burrito": "부리토",
  "Small Refresh": "소소한 회복",
  "Enchanted item": "마법 부여된 아이템",
  "Colander": "체",
  "Dishwasher": "식기세척기",
  "Mittel": "미텔",
  "Boulder Trap": "거대한 바위 함정",
  "Plains of Edin": "에딘의 동산",
  "Honeycomb": "벌집",
  "Blood Price": "피의 대가를 치른다",
  "Zoarcid": "등가시치",
  "Slumbering Primordial": "잠든 원시의 존재",
  "Scare It": "겁준다",
  "Narwhal": "일각고래",
  "Artist Alley": "예술가 거리를 방문한다",
  "Dungeon move forward 1": "Dungeon move forward 1",
  "Serving Platter": "요리 쟁반",
  "Medic's Shield": "의무병의 방패",
  "Pop Snappers": "콩알탄",
  "Foundation Revenant": "지저 망령",
  "Shoe Blade": "신발 칼날",
  "Sulphur": "유황",
  "Weaponized Core": "무기화 코어",
  "Jumbo Wok": "점보 웍",
  "Rice Cooker": "전기밥솥",
  "Chocolate Bar": "초코바",
  "Pile of Gold 4": "골드 더미 4",
  "Spices": "향신료",
  "Valpak": "발팩",
  "Premium Chocolate Bars": "프리미엄 초코바",
  "Petrifying Gaze": "석화의 시선",
  "Health Training": "체력 훈련",
  "Cornucopia": "풍요의 뿔",
  "Ganjo": "간조",
  "Distilled Sunlight": "증류된 햇빛",
  "Depth Charge": "폭뢰",
  "Toxic Friendship": "유독한 우정",
  "Gold": "골드",
  "Uwashiwali Bird": "우와시왈리 새",
  "Arc Blaster": "전격 발사기",
  "Concealed Dagger": "숨겨둔 단검",
  "Bounty Hunters": "현상금 사냥꾼",
  "Quick Freeze": "빠른 빙결",
  "Curry": "카레",
  "Trash Golem": "쓰레기 골렘",
  "Display Case": "전시장",
  "Knife Tricks": "단검 묘기",
  "Tea Siphon": "차 추출기",
  "Coolant Leak": "냉각수 누출",
  "Giant Mosquito": "거대 모기",
  "Paper Airplane": "종이비행기",
  "[DEBUG] End of Fight Transform": "텍스트 누락",
  "Chemical Fire": "화학 불길",
  "Remote Control": "리모컨",
  "Caviar": "캐비아",
  "Citrus": "감귤류",
  "Soulstone": "영혼석",
  "Swag Collector": "물건을 수집한다",
  "Blow Torch": "용접 토치",
  "Enchant Obsidian": "흑요석 마법 부여",
  "Cosmic Plumage": "우주의 깃털",
  "Vengeance": "복수",
  "Sterling": "스털링",
  "Insect Bite": "벌레에게 물림",
  "Schematics": "설계도",
  "Rice": "쌀",
  "Critical Aid": "결정적 지원",
  "Shot Glasses": "술잔",
  "Dam": "댐",
  "Vitality Potion": "활력 물약",
  "Big Ego": "비대한 자아",
  "Strength": "힘",
  "Pierre Conditioner": "에어컨 피에르",
  "Honed Strike": "날카로운 타격",
  "Prosperity": "번영",
  "Rex Spex": "렉스 스펙스",
  "Altimeter": "고도계",
  "Streaming Setup": "스트리밍 장비",
  "Viper Tyrant": "독사 폭군",
  "Ferros Khan": "페로스 칸",
  "Smelling Salts": "지독한 소금",
  "Aurora Dome": "오로라 돔",
  "Defense Matrix": "방어 매트릭스",
  "Refrigerator": "냉장고",
  "Trained Spider": "훈련받은 거미",
  "Test Subject Alpha": "실험체 알파",
  "Invigorating Blade": "활력의 검",
  "Shatter": "산산조각",
  "Pylon": "전력탑",
  "Chaff": "교란 장치",
  "Haladie": "할라디",
  "Switchblade": "잭나이프",
  "Bottled Tornado": "병에 담은 토네이도",
  "Adrenal Converter": "아드레날린 전환기",
  "Bloodreef Captain": "블러드리프 선장",
  "Microfiber": "극세사섬유",
  "Yo-Yo": "요요",
  "Safe": "금고",
  "Emerald": "에메랄드",
  "Flamewright": "화염술사",
  "Snow Globe": "스노우 글로브",
  "All Talk": "허풍쟁이",
  "Virtual PVP Alsace": "가상 PVP 알사스",
  "Iceberg": "빙산",
  "Herbal Supplements": "약초 보충제",
  "Silvia": "실비아",
  "Chef of War": "전쟁의 요리사",
  "Ice Swan": "얼음 백조",
  "[SMALL ITEM TEMPLATE]": "[SMALL ITEM TEMPLATE]",
  "Treasure Trove": "보물 창고",
  "Cold Room": "추운 방",
  "Searing Flames": "타오르는 불꽃",
  "Monster Ranch": "몬스터 거주지",
  "Busy Bee": "바쁜 벌",
  "Seaweed": "해초",
  "[LARGE ITEM TEMPLATE]": "[LARGE ITEM TEMPLATE]",
  "Rapid Thaw": "급속 해동",
  "Crow's Nest": "망대",
  "Deluxe Chocolate Bars": "디럭스 초코바",
  "Collect Earnings": "수익금 수집",
  "Arms Race": "군비 경쟁",
  "Custom Scope": "맞춤형 조준경",
  "Philosopher's Stone": "현자의 돌",
  "Mirror": "거울",
  "Chronobarrier": "시간 장벽",
  "Forbidden!": "금지됨!",
  "Premium Set": "명품 세트",
  "Metronome": "메트로놈",
  "Wish for Fame": "명성을 소망한다",
  "Reinforce Firewall": "방화벽 강화",
  "Gatling Gun": "게틀링 건",
  "Radiant Corsair": "광휘의 해적",
  "Rigged": "속임수",
  "Captain's Quarters": "선장 구역",
  "protein powder": "단백질 보충제",
  "Sparring Partner": "스파링 파트너",
  "Luxe": "럭스",
  "Wild Strength": "야생의 힘",
  "Wandering Shoal": "떠도는 물고기떼",
  "Wrist Warrior": "손목 전사",
  "Satchel": "가방",
  "Trade It for Something": "무언가와 교환한다",
  "Clean Storefront": "깔끔한 상점",
  "Pygmalien's Loft": "피그말리엔의 다락방",
  "Grandmaster": "대가",
  "Upgrade All Bronze": "모든 브론즈 등급을 강화합니다",
  "Blazehowl Warden": "화염포효 수호자",
  "Dragon": "드래곤",
  "Watch the Game": "게임을 구경한다",
  "Aviators": "비행사 선글라스",
  "Street Food": "길거리 음식",
  "Heated Shells": "가열된 탄약",
  "Haddy": "해디",
  "Observatory": "천문대",
  "Runic Daggers": "룬 단검",
  "Launch Pad": "발사대",
  "Thirsty": "갈증",
  "Catfish": "메기",
  "First Flames": "첫 번째 불꽃",
  "Keen Eye": "예리한 눈",
  "Work as Inspector": "검사관으로 일합니다",
  "Butterfly Swords": "나비 단검",
  "Left Eye": "왼쪽 눈",
  "Thieves Guild Medallion": "도둑 길드 훈장",
  "Large Item Specialist": "대형 아이템 전문가",
  "IllusoRay": "환영레이",
  "Chocolate Coin": "초콜릿 동전",
  "Take Flight": "비행기 탑승",
  "Uncle Odi": "오디 삼촌",
  "Poison Blades": "독 칼날",
  "Scrap": "고철",
  "Play Marbles with Likit": "리키트와 구슬 놀이를 한다",
  "Nonna": "노나",
  "[DEBUG] Hacked Quest Debug": "텍스트 누락",
  "The Best Defense": "최고의 방어",
  "Motherboard": "메인보드",
  "Capacitor": "축전기",
  "Blank Slate": "비어있는 석판",
  "Master Salesman": "장사의 달인",
  "Reinforce": "보강한다",
  "Integrated HUD": "일체형 HUD",
  "Bayonet": "총검",
  "Goggles": "보안경",
  "Staff of the Moose": "무스의 지팡이",
  "Staying Power": "지구력",
  "Momma-Saur": "마마사우루스",
  "Knightshade": "나이트셰이드",
  "Singularity": "특이점",
  "Universal Sauce": "만능 소스",
  "Volkas Enforcer": "볼카스 집행관",
  "Ramrod": "장전봉",
  "Curio": "큐리오",
  "Mortal Coil": "필멸의 채찍",
  "Fate's Fortunes": "운명적인 행운",
  "Shrinking Potion": "축소 물약",
  "Improvised Weaponry": "임시 무기",
  "Sharpen Weapon": "무기 날 세우기",
  "Laser Pistol": "레이저 권총",
  "Middle of the Pack": "중간 무리",
  "Suprise Mushroom - Stronger": "깜짝 버섯 - 강화",
  "Fiber Optics": "광섬유",
  "Heat Shield": "열 차단막",
  "Health Spark": "체력의 불꽃",
  "Corrosive Toxins": "부식성 독소",
  "Cellar": "지하실",
  "Plasma Rifle": "플라즈마 소총",
  "Star Chart Treasure": "별자리 지도 보물",
  "Rocket Drone": "로켓 드론",
  "Capital Gains": "자본 이득",
  "Grill": "그릴",
  "Void Golem": "공허의 골렘",
  "Cookie Cutters": "쿠키 틀",
  "Oceanic Rush": "대양의 질주",
  "Javalin": "자벨린",
  "Catalyst": "촉매제",
  "Green Piggles A": "초록 피글스 A",
  "Textiles": "섬유",
  "Spin the Wheel": "룰렛 돌리기",
  "Virus": "바이러스",
  "Black Ice": "검은 얼음",
  "Large Poisons": "대형 독",
  "Heavy Mettle": "강철 정신",
  "Hard Shell": "단단한 껍질",
  "PenFT": "펭FT",
  "Private Hot Springs": "개인 온천",
  "Augmented Weaponry": "증강된 무기",
  "Bladeborn Badlands": "칼날의 황무지",
  "Water Wheel": "물레방아",
  "Poisonous Opener": "독약병따개",
  "Haunted Kimono": "유령 기모노",
  "Flycycle": "비행 자전거",
  "[DEBUG] Disable / Destroy": "텍스트 누락",
  "Relax": "휴식",
  "Ice 9000": "아이스 9000",
  "Cutlass": "커틀러스",
  "Aerodrome": "비행장",
  "Luxury Tents": "고급 텐트",
  "Shored Up": "보강",
  "Pufferfish": "복어",
  "Get Gold Loot": "골드 등급 전리품 획득",
  "Apothecary": "약방",
  "Recycling Center": "재활용 센터",
  "Flurry of Blows": "연격",
  "Collect Spare Change": "잔돈 수집",
  "Hydrogen Tank": "수소 탱크",
  "Eli": "엘리",
  "Dooltron": "둘트론",
  "Defender": "수호자",
  "Shrouded Figure's Chest": "수수께끼의 인물의 상자",
  "Stealth Glider": "스텔스 글라이더",
  "Side Hustle": "부업",
  "Big Guns": "대형 포",
  "Apprentice Banehand": "견습 독술사",
  "BLK-SP1D3R": "흑-7ㅓㅁ1",
  "Borrow": "대출",
  "Firestarter": "방화범",
  "Goldie": "골디",
  "Baked Potato": "구운 감자",
  "Birthday Cake": "생일 케이크",
  "Lightning Rod": "피뢰침",
  "Flail": "도리깨",
  "Main Course": "메인 코스",
  "Carving Fork": "요리용 포크",
  "Grater": "강판",
  "Full Course Meal": "풀코스 요리",
  "The Greenheart": "그린하트",
  "Char Cole": "석탄이",
  "Dire Mosquito": "무시무시한 모기",
  "Clawrence": "클로렌스",
  "Marble Scalemail": "대리석 비늘 갑옷",
  "Aleppa Tantius": "알레파 탄티우스",
  "Atlatl": "아틀라틀",
  "Rifle": "소총",
  "Explosive Potions": "폭발 물약",
  "Outlands Dervish": "황무지 데르비시",
  "Vanessa's Quarters": "바네사의 숙소",
  "Master Mechanic": "달인 정비사",
  "Mental Breakthrough": "정신적 돌파구",
  "Farai": "파라이",
  "Tesla Coil": "테슬라 코일",
  "Hunt for Reagents": "시약을 찾는다",
  "Arken's Ring": "아르켄의 반지",
  "Decline": "거절",
  "Eagle Talisman": "독수리의 부적",
  "Pyre": "장작더미",
  "Toughness": "강인함",
  "Lord Arken": "군주 아르켄",
  "Diamond Skill": "다이아몬드 등급 스킬",
  "Master Alchemist": "달인 연금술사",
  "Memento Mori": "메멘토 모리",
  "Arms Locker": "무기 보관함",
  "Slow and Steady": "느리지만 착실하게",
  "Salesmanship": "영업술",
  "Hulking Experiment": "거대한 실험체",
  "The Tester": "연구자",
  "Reagent Shelf": "시약 선반",
  "Work as Security": "보안 요원으로 일한다",
  "[EVENT TEMPLATE]": "[EVENT TEMPLATE]",
  "Old Barrel": "낡은 통",
  "Claw Game": "집게 놀이",
  "Hammock": "해먹",
  "Freezer": "냉동고",
  "Farmer's Market": "농부 시장",
  "Aila": "아일라",
  "Zosima": "조시마",
  "Fire Bomb": "화염 폭탄",
  "1st Quarter": "1쿼터",
  "Dungeon Rare Dragon combat reward": "던전 레어 드래곤 전투 보상",
  "[DEBUG] Time Contraction": "텍스트 누락",
  "Chef Brolin": "브롤린 셰프",
  "Paralytic Poison": "마비독",
  "Tropical Island": "열대 섬",
  "Flanking Shots": "측면 사격",
  "Hot Air": "열기류",
  "Joyful Jack Reward": "즐거운 잭 보상",
  "Tracer Fire": "화염 추적",
  "Aldric": "알드릭",
  "Trebuchet": "트레뷰셋",
  "Ledger": "거래 장부",
  "Sword Cane": "검 지팡이",
  "Nightshade": "나이트셰이드",
  "Pitchfork": "쇠스랑",
  "Ice Cream Truck": "아이스크림 트럭",
  "Belt": "벨트",
  "Well-Oiled Machine": "기름칠 잘된 기계",
  "Right-Handed": "오른손잡이",
  "Aerial Turret": "공중 포탑",
  "Power Broker": "권력 중개인",
  "Sonic Cannon": "음향포",
  "Premium Pass": "프리미엄 패스",
  "Forged Fortune": "단조된 재물",
  "Crusher Claw": "파쇄 집게",
  "Add It to Your Bushel": "내 바구니에 넣는다",
  "Happiness": "행복",
  "Mr. Morland": "모랜드 씨",
  "One Shot, One Kill": "한 발에 한 놈",
  "Sea Shell": "조개 껍질",
  "Mythkeeper": "신화수호자",
  "Pawn Shop": "전당포",
  "Upgrade Hammer": "강화 망치",
  "Frozen Shot": "얼어붙은 사격",
  "Nimble": "민첩한",
  "Critical Investments": "결정적 투자",
  "Ice Claw": "얼음 발톱",
  "Honing Steel": "연마봉",
  "Darts": "다트",
  "Knife Set": "식칼 세트",
  "Spirit Diffuser": "영혼 확산기",
  "Stained Glass Window": "스테인드 글래스 창문",
  "Masterpiece": "걸작",
  "Access the Vault": "금고에 접근한다",
  "Levitation Pad": "공중부양 판",
  "Parachute": "낙하산",
  "Inheritance": "상속",
  "Sharkclaws": "상어 발톱",
  "Enjoy the Scenery": "경치를 감상한다",
  "Burn Training": "화염 훈련",
  "Vitality Stew": "활력의 스튜",
  "Expand": "확장",
  "Giant Sub": "거대 잠수함",
  "Microwave": "전자레인지",
  "Quick Bite": "빠른 물기",
  "Cryomastery": "냉기 숙련",
  "Purifying Flame": "정화의 불꽃",
  "Lowroller": "로우롤러",
  "Ionized Lightning": "이온화된 번개",
  "Stew": "스튜",
  "Feast": "연회",
  "Specialist": "전문가",
  "[MEDIUM ITEM TEMPLATE]": "[MEDIUM ITEM TEMPLATE]",
  "Tea Set": "차 세트",
  "Kukri": "쿠크리",
  "Armored Core": "장갑 코어",
  "Drafting Table": "도면 테이블",
  "Grindstone": "연마석",
  "Precision Calipers": "정밀한 측정기",
  "Nanobot Green": "나노봇 그린",
  "Enchant Shiny": "반짝이는 마법 부여",
  "Clockwork Disc": "시계태엽 원반",
  "Extract Extract": "추출물 추출",
  "Escape to the Sea": "바다로 도망친다",
  "A Strange Mushroom": "이상한 버섯",
  "Cryosphere": "빙구",
  "Put Up a Billboard": "광고판을 설치한다",
  "Beta Ray": "베타 레이",
  "Grab Bag": "경품 상자",
  "Oven": "오븐",
  "Medic's Aid": "의무병의 지원",
  "Junkyard Catapult": "고물장 투석기",
  "Orly": "오를리",
  "Flattened!": "납작!",
  "Apropos Chapeau": "멋진 모자",
  "Trained with a Traveling Monk": "여행 중인 수도승과 훈련합니다",
  "Lighter": "라이터",
  "Seadog's Saloon": "노련한 해적의 술집",
  "Buy Some Team Merch": "팀 머치에게서 구매한다",
  "Eight Arm Davvy": "여덟팔 데비",
  "Scales": "저울",
  "Corkscrew": "코르크따개",
  "Eccentric Etherwright": "괴짜 에테르장인",
  "Core Initialization": "코어 초기화",
  "Purify": "정화한다",
  "Fate's Crossroads": "운명의 갈림길",
  "Weather Machine": "날씨 기계",
  "Feather": "깃털",
  "Large Investment Payout": "대규모 투자 지급",
  "Infernal": "인페르날",
  "Balanced Specialist": "균형 잡힌 전문가",
  "Snowstorm": "폭설",
  "Athanor": "연금로",
  "Pinfeather": "핀페더",
  "Angry Balloon Bot": "분노한 풍선 로봇",
  "Pal Around": "친구로 지내기",
  "Jungle Ruins": "정글 폐허",
  "Alchemy Lab": "연금술 실험실",
  "Improvised Burn": "임시 연소",
  "Rowboat": "노젓는 배",
  "Shields Up": "방패 올리기",
  "Stellar Swallowtail": "별빛 제비꼬리",
  "Heirlooms": "가보",
  "Flex": "플렉스",
  "Heavy Weaponry": "중화기",
  "Thieves Guild": "도둑 길드",
  "Finesse Shield": "정교한 방패",
  "Battle Drone": "전투 드론",
  "Ectoplasm": "심령체",
  "Bex": "벡스",
  "Return It": "되돌려 놓는다",
  "Lost Treasure": "잃어버린 보물",
  "Ande": "앤디",
  "Skillet": "프라이팬",
  "Hogwash": "돼지세탁소",
  "Product Demonstrator": "제품 시연사",
  "Viper Rewards": "독사 보상",
  "Radar Module": "레이더 모듈",
  "Retool": "재정비",
  "Jellyfish": "해파리",
  "Compass": "나침반",
  "Ray Training": "레이 훈련",
  "Standardized Defenses": "표준화된 방어체계",
  "The Right Tool": "딱 맞는 도구",
  "Rapid Injection System": "급속 주입 장치",
  "Dock Lines": "계류 밧줄",
  "Frontal Shielding": "전방 방어",
  "It's Yours!": "당신 것입니다!",
  "Big Bad Wolf": "커다란 나쁜 늑대",
  "Skyliner": "하늘선",
  "Static Acceleration": "정전기 가속",
  "Spider Mace": "거미 철퇴",
  "Makeshift Plate": "임시 방어판",
  "Salt": "소금",
  "Berserker": "광전사",
  "Subscraper": "수중수집가",
  "Gaseo": "가세오",
  "Creeping Chill": "스며드는 한기",
  "Candy Collector": "사탕 수집가",
  "Cyclops Eye": "사이클롭스의 눈",
  "Lefty Loosey": "왼쪽으로 풀기",
  "Noxious Potion": "독성 물약",
  "Table Setting": "테이블 준비",
  "Isochoric Freezer": "등적 냉각기",
  "Robe": "로브",
  "Battlefield": "전장",
  "Gavel": "판사 망치",
  "Bet on the Roughtown Kyvers": "러프타운의 카이버들에게 건다",
  "Choose Power": "힘을 고른다",
  "Clamera": "백합메라",
  "Kyver Drone": "카이버 병사",
  "Wish for Immortality": "불멸을 소망한다",
  "[DEBUG] Other Flying": "텍스트 누락",
  "Chef Hat": "요리사 모자",
  "Mr. Moo": "음메 씨",
  "Third Degree Burns": "3도 화상",
  "Thrown Net": "투망",
  "Lion Cane": "사자 지팡이",
  "Green Light": "초록불",
  "Multitool": "만능 도구",
  "Super Syrup": "특제 시럽",
  "Infernal Envoy": "인페르날 사절",
  "Guardian's Fury": "수호자의 분노",
  "Smoke Detector": "연기 감지기",
  "Renovation": "개조",
  "Found a Healing Spring": "치유의 샘을 발견했습니다",
  "Work as Dockhand": "부두 일꾼으로 일한다",
  "Return the Crate to Its Owner": "상자를 주인에게 돌려둔다",
  "Bootstraps": "부트스트랩",
  "Pumpkin": "호박",
  "[DEBUG] Temporary Enchantment": "텍스트 누락",
  "Dingle Ingle": "딩글 잉글",
  "Emergency Burn": "긴급 점화",
  "Harmadillo": "악마딜로",
  "Assault Focus": "공격 집중",
  "Aerial Assault": "공중 공격",
  "Ancient Vengeance": "고대의 복수",
  "Quixel": "퀵셀",
  "Vital Renewal": "생명 회복",
  "Drone Training": "드론 훈련",
  "Supply Cache": "물자 비축소",
  "Artisan Dunes": "장인의 사구",
  "Small item Specialist": "소형 아이템 전문가",
  "Toughness Training": "강인함 훈련",
  "Scovyle": "스코빌",
  "Orbital Polisher": "회전 연마기",
  "Cleaver": "식칼",
  "Parting Shot": "최후의 한방",
  "Greenheart Guardian": "그린하트 수호자",
  "Tortuga": "토르투가",
  "[DEBUG] Fate's Fortunes Enchant": "텍스트 누락",
  "Tranquil Spring": "평온의 샘",
  "Hostile Takeover": "적대적 인수를 한다",
  "Gain 100 Max Health": "100의 최대 체력을 얻습니다",
  "Laser Security System": "레이저 보안 시스템",
  "Toxic Fuel": "유독성 연료",
  "Repeater": "연발총",
  "Viper Cane": "독사 지팡이",
  "Procure Medkit": "의료 키트 획득",
  "Tanky Anky": "튼튼한 안킬로",
  "Aggressive Mutations": "공격적 돌연변이",
  "Strength Training": "근력 훈련",
  "SMG Cache": "SMG 저장고",
  "Miss Isles": "미스 아일",
  "Fungal Spores": "곰팡이 포자",
  "Premium Red Piggles": "고급형 빨강 피글스",
  "Chilly Charles": "차가운 찰스",
  "Foreboding Winds": "불길한 바람",
  "Counterstrike": "반격",
  "Enjoy some Stadium Snacks": "경기장 간식을 즐긴다",
  "Augmented Defenses": "증강된 방어",
  "Chicken Cannon": "닭 대포",
  "Temporal Strike": "순간 타격",
  "[ENCOUNTER STEP TEMPLATE]": "[ENCOUNTER STEP TEMPLATE]",
  "Tiny Furry Monster": "작은 털복숭이 몬스터",
  "Pyro": "파이로",
  "Sharpshooter": "명사수",
  "Lumboars": "통나무노",
  "Regal Blade": "왕실의 검",
  "Stinger": "독침",
  "In-Flight Meal": "기내식",
  "Regenerative": "재생",
  "Rear Shielding": "후방 방어",
  "Rivet Gun": "못 발사기",
  "Sandbags": "모래주머니",
  "Orion": "오리온",
  "Combat Training": "전투 훈련",
  "Building Crescendo": "점점 강하게",
  "Chunk of Gold": "금 덩어리",
  "Heat Lover": "불꽃성애자",
  "Booby Trap": "부비트랩",
  "Lost Wallet": "잃어버린 지갑",
  "Ice Bomb": "얼음 폭탄",
  "Zoot Flute": "화려한 피리",
  "Sunlight Spear": "태양광 창",
  "Poison Tyrant": "독의 폭군",
  "Soldering Gun": "납땜 총",
  "Excavation Tools": "발굴 도구",
  "Space Laser": "우주 레이저",
  "Immunocompromised": "면역력 저하",
  "Abandoned Property": "버려진 자산",
  "Venomous Vitality": "독의 활력",
  "Refractor": "굴절기",
  "Plague Glaive": "역병 글레이브",
  "Weights": "무게 추",
  "Target Acquisition": "목표 고정",
  "Sharpening Stone": "숫돌",
  "The Roughtown Kyvers Win!": "러프타운의 카이버들이 이겼습니다!",
  "Fiery Rebirth": "불꽃 재탄생",
  "Mandala": "만달라",
  "Stelle": "스텔",
  "[DEBUG] Decharge Test": "텍스트 누락",
  "Covetous Raven": "탐욕스러운 까마귀",
  "Introspection": "자기 반성",
  "Amber": "호박",
  "Combat Medic": "전투 의무병",
  "Foundation Weeper": "지저 비명자",
  "Crypto": "암호화폐",
  "Nautica": "나우티카",
  "Premium Green Piggles": "고급형 초록 피글스",
  "Sky Anchor": "하늘 닻",
  "Cloudtop Admiral": "클라우드톱 제독",
  "Beast of Burden": "짐꾼 짐승",
  "Stop That!": "그만 해!",
  "Focused Core": "집중 코어",
  "Regeneration Potion": "재생 물약",
  "GPU": "GPU",
  "Flashy Pilot": "화려한 조종사",
  "Foraged Mushrooms": "채집한 버섯",
  "Full Arsenal": "완전 무장",
  "Disguise": "변장",
  "Wallace": "월리스",
  "[DEBUG] Perm Destroy": "텍스트 누락",
  "Thermal Lance": "고열 창",
  "Improve Friendship": "우정을 개선한다",
  "Streamline Weapon": "날렵한 무기",
  "Lash Out": "독 한방 날리기",
  "Dino Trapping": "공룡 포획",
  "The Lost Crate": "잃어버린 상자",
  "Life Preserver": "구명 용품",
  "Vortex Cannon": "소용돌이 대포",
  "Silk Scarf": "비단 스카프",
  "Defense Grid": "방어 그리드",
  "Skewer": "꼬치",
  "The Big One": "빅 원",
  "Oxygen Mask": "산소 마스크",
  "Solar Farm": "태양광 발전소",
  "Marshalling Lights": "유도등",
  "Blue Piggles A": "파랑 피글스 A",
  "Beehive": "벌집",
  "Trader": "상인",
  "Transform Large": "대형 아이템을 변환한다",
  "Laurel's Fortress": "로렐의 요새",
  "Cauterize": "지지기",
  "Mouse Trap": "쥐덫",
  "Toxin Injector": "독소 주입기",
  "Security Drone": "보안 드론",
  "Play With It": "함께 논다",
  "Flanking Toxins": "측면 독소 공격",
  "Trail Mix": "견과류",
  "Hot Sauce": "핫 소스",
  "Red Piggles R": "빨강 피글스 R",
  "Korxena Crest": "코르세나 문장",
  "Pile of Gold 6": "골드 더미 6",
  "Economic Seminar": "경제 강연",
  "Battle Balloon": "전투 열기구",
  "Thurible": "향로",
  "Ambush": "매복",
  "Plasma Grenade": "플라즈마 수류탄",
  "Orange Piggles R": "주황 피글스 R",
  "Proboscis": "주둥이",
  "Astrolabe": "천체의",
  "Dumpster Diving": "폐기물 수색",
  "Barrel": "통",
  "Gyro Gunsight": "회전식 조준경",
  "Anemometer": "풍속계",
  "Rise to the Challenge": "도전에 맞선다",
  "Power Training": "파워 트레이닝",
  "Tusked Helm": "엄니 헬멧",
  "Succulents": "다육식물",
  "Cog": "톱니바퀴",
  "Caltrops": "마름쇠",
  "Command Ship": "지휘선",
  "Double Barrel": "이중 총열 총",
  "Temple Expedition": "사원 탐험",
  "Share It With a Friend": "친구랑 나눈다",
  "Bounty Hunter": "현상금 사냥꾼",
  "Orange Piggles L": "주황 피글스 L",
  "Racetrack": "경주장",
  "Dabbling Apprentice": "미숙한 견습생",
  "Small Package": "소형 패키지",
  "Street Gamer": "길거리 게이머",
  "Lightning Butterfly": "번개 나비",
  "Networking": "교류한다",
  "Captain's Charge": "선장의 돌격",
  "Continue": "계속",
  "Exceed": "초과",
  "Critical Captain": "치명적인 선장",
  "Mysterious Portal": "신비한 포털",
  "Basilisk Fang": "바실리스크 송곳니",
  "Showcase Arsenal": "무기 진열장",
  "Cosmic Wind": "우주풍",
  "Powder Horn": "휴대용 화약통",
  "The Cult": "광신도 집단",
  "Retort": "증류기",
  "Coconut Crab Rewards": "코코넛 크랩 보상",
  "Memory Card": "메모리 카드",
  "Whisk": "거품기",
  "Serafina": "세라피나",
  "Balanced Friendship": "조화로운 우정",
  "Unstable Grav Well": "불안정한 중력장",
  "Volcanic Vents": "용암 분출구",
  "Vial Launcher": "시약병 발사기",
  "Arms Dealer": "무기 상인",
  "Retiree": "은퇴자",
  "Tripwire": "함정줄",
  "Sell Ice Cream at the Festival": "축제에서 아이스크림을 판매합니다",
  "Orange Julian": "오렌지 줄리안",
  "Primal Core": "원시 코어",
  "Trollosaur": "트롤로사우루스",
  "Runic Great Axe": "룬 대형도끼",
  "Infused Bracers": "주입형 팔보호구",
  "Radar Dome": "탐지 돔",
  "Pulse Rifle": "펄스 소총",
  "Languid Dunes": "영겁의 사구",
  "Private Flight": "전용기",
  "Left-Handed": "왼손잡이",
  "Matchbox": "성냥갑",
  "Rogue Scrapper": "떠돌이 수집가",
  "Keen Edge": "날카로운 칼날",
  "Critical Protector": "치명적인 수호자",
  "Hard Assets": "실물 자산",
  "Heavy Firepower": "강력한 화력",
  "Excavation": "발굴",
  "Oven Mitts": "오븐 장갑",
  "Bombing Run": "폭격 작전",
  "Street Festival": "거리 축제",
  "Chronos": "크로노스",
  "Briefcase": "서류가방",
  "Ulu Knife": "울루 나이프",
  "Frozen Synapse": "빙결된 회로",
  "Toy Training": "장난감 훈련",
  "Wrench": "스패너",
  "Alchemical Precision": "정밀 연금술",
  "Flint Stones": "부싯돌",
  "Liquid Cooled": "수냉",
  "Mortar & Pestle": "막자사발과 막자",
  "Improvised Heal": "임시 치료",
  "Gain 8 Gold": "8 골드를 얻습니다",
  "Ahexa": "아헥사",
  "Piranha": "피라냐",
  "Lost and Found": "분실물 찾기",
  "Money Furnace": "돈용광로",
  "The Tome of Yyahan": "야한의 서",
  "Revolver": "리볼버",
  "Micro Dave": "전자레은지",
  "Vending Machine": "자판기",
  "Collect Gold": "골드를 수집합니다",
  "Spice Rack": "향신료 선반",
  "Thanks!": "고마워!",
  "Frozen Bludgeon": "얼음 곤봉",
  "Oni Mask": "오니 가면",
  "Zarlic": "자릭",
  "Morguloth": "모르굴로스",
  "Flanking Aid": "측면 지원",
  "Rebel Hideout": "반군 은신처",
  "Pyg's Gym": "피그의 체육관",
  "Brick Buddy": "벽돌 친구",
  "Grenade": "수류탄",
  "Diving Helmet": "잠수 헬멧",
  "Draconic Rage": "드래곤의 분노",
  "Gravstone": "부유석",
  "Friendship is Magic": "우정은 마법",
  "Palanquin": "가마",
  "High Impact": "강력한 영향",
  "Thick Hide": "두꺼운 가죽",
  "Forage": "채집",
  "Lunch Box": "도시락",
  "Lemonade Stand": "레모네이드 가게",
  "Coolant": "냉각제",
  "Tomb of the Ancients": "고대인의 무덤",
  "Valley Fever": "계곡 열병",
  "Riceballer": "주먹밥 튀김기",
  "Vital Reserve": "생명 비축",
  "Ouroboros Statue": "우로보로스 조각상",
  "Advanced Synthetics": "고급 합성소재",
  "Sharpening Kit": "연마 키트",
  "Diamond Fangs": "다이아몬드 송곳니",
  "Bronze-tier Merchant": "브론즈 등급 상인",
  "Junkyard Lance": "고물장 창",
  "Hacksaw": "쇠톱",
  "Ammo Stash": "탄약 비축",
  "Property Mogul": "부동산 재벌",
  "Hef": "헤프",
  "Thrill of the Flight": "비행의 짜릿함",
  "Piggles": "피글스 세트",
  "Cove": "작은 만",
  "Commercial Zoning": "상업 지역",
  "Burn Containment": "화염 통제",
  "Regain Resolve": "결의 회복",
  "Knee Brace": "무릎 보호대",
  "Housewarming Gifts": "집들이 선물",
  "Financial District - Gain Health": "금융 지구 - 체력 얻기",
  "Pet It": "쓰다듬는다",
  "Igloo": "이글루",
  "Grandfather Klok": "클록 할아버지",
  "Weapons Platform": "무기 플랫폼",
  "Cash Deposits": "금융 치료",
  "Pesky Pete": "성가신 피트",
  "Prime Real Estate": "최고급 토지",
  "Cabin Fishing": "오두막 낚시",
  "Neophiliac": "신문물 애호가",
  "Hang Glider": "행글라이더",
  "Elemental Depth Charge": "원소 폭뢰",
  "Headset": "헤드셋",
  "Buckle Up!": "안전벨트 매기!",
  "Omega Ray": "오메가 레이",
  "Ritual Dagger": "의식용 단검",
  "Walk-in Clinic": "예약 없는 진료소",
  "Jules' Cafe": "줄스의 카페",
  "Artillery Spotter": "포병 관측병",
  "Amuse Bouche": "즐거운 부시",
  "Frostfire": "서리불꽃",
  "Gramophone": "축음기",
  "Cannonade": "연속포격",
  "[DEBUG] Day Hour Replacement EncounterStep": "텍스트 누락",
  "Aludel": "승화기",
  "Calcinator": "소성기",
  "Giant Lollipop": "거대한 막대사탕",
  "Lighthouse": "등대",
  "Crane": "크레인",
  "Darkwater Anglerfish": "심해의 아귀",
  "Pressure Heater": "고압 가열기",
  "Titanium Casing": "티타늄 장갑",
  "Net Launcher": "그물 발사기",
  "Plasma Whip": "플라즈마 채찍",
  "Shard of Obsidian": "흑요석 조각",
  "Grab the Loot": "전리품을 챙긴다",
  "Atlas": "아틀라스",
  "Wand": "완드",
  "Toxic Shield": "유독성 보호막",
  "Jury Rigger": "임시 수리공",
  "Workshop": "작업장",
  "Frozen Horror": "얼어붙은 공포",
  "Heat Sync": "열 동기화",
  "Chris Army Knife": "군용 칼 크리스",
  "Egg Timer": "계란 타이머",
  "Fate's Legacy": "운명의 유산",
  "Free Ride": "무임 승차",
  "Poison Training": "중독 훈련",
  "Blowgun": "블로우건",
  "Pepper": "후추",
  "Pogo Stick": "포고 스틱",
  "Moon Orb": "달 구체",
  "Sharpen": "날 세우기",
  "Passive Power": "패시브의 힘",
  "Herb Shears": "정원 가위",
  "Skyterror": "하늘의공포",
  "Reinforce Equipment": "장비 강화",
  "Focused Rage": "집중된 분노",
  "Ballista": "발리스타",
  "Charged Up": "충전됨",
  "Temporal Navigator": "시간 항해자",
  "Steady Defender": "안정적인 수호자",
  "Apron": "앞치마",
  "Mr. Tuskari": "투스카리 씨",
  "Yeti Crab": "예티 크랩",
  "Strong Arm": "강압",
  "Blunderbuss": "나팔총",
  "Ramming Balloon": "돌격 열기구",
  "Desperate Cleanse": "필사적 정화",
  "Confidential Information": "기밀 정보를 캐낸다",
  "Hydraulic Squeezer": "유압 압착기",
  "Rolling Pin": "밀대",
  "Steelstorm": "강철폭풍",
  "Deep Sea Fishing": "심해 낚시",
  "Standard Flight": "기본 항공편",
  "Fanged Inglet Rewards": "송곳니 잉글릿 보상",
  "Loaded Fury": "장전된 분노",
  "Rune Axe": "룬 도끼",
  "Forgotten God": "잊힌 신",
  "Tournament Arena": "토너먼트 경기장",
  "Quicksilver": "수은",
  "Welding Torch": "용접 토치",
  "Eject Button": "사출 버튼",
  "Snowflake": "눈송이",
  "Ghost Pepper": "유령 고추",
  "Warrior": "전사",
  "[DEBUG] Disenchant": "텍스트 누락",
  "Burninator Bot": "화염파괴 로봇",
  "Ignition Core": "점화 코어",
  "Fortune Cookie": "포춘 쿠키",
  "Vat of Acid": "산성 통",
  "Equivalent Exchange": "등가 교환",
  "Sick Burn": "맹독 화상",
  "Soul of the District": "구역의 영혼",
  "Fire Hose": "소방 호스",
  "Antimatter Chamber": "반물질 저장실",
  "Exoskeleton": "외골격",
  "First Strike": "첫번째 타격",
  "Crimson Dash": "진홍빛 돌진",
  "Cooling Fan": "냉각 팬",
  "Toxic Door": "유독성 문",
  "Hardened Shield": "단단해진 방패",
  "Pinata": "피냐타",
  "Armory": "병기고",
  "Healthy Lifestyle": "건강한 생활",
  "Food Truck": "푸드 트럭",
  "Regular Set": "정규 세트",
  "Hearty Breakfast": "든든한 아침식사",
  "BLU-B33TL3": "청-4슴벌레",
  "Party Float": "공중 파티선",
  "Void Ray": "공허 레이",
  "Fixer Upper": "허름한 집",
  "Spacescraper": "우주 마천루",
  "Boiling Flask": "끓는 플라스크",
  "Fang": "송곳니",
  "Beach Ball": "비치볼",
  "Final Flame": "마지막 불꽃",
  "Captain's Wheel": "선장의 조타륜",
  "The One Potion": "물약 하나",
  "Makroscope": "막미경",
  "Mini Fridge": "소형 냉장고",
  "Waters of Infinity": "무한의 물",
  "Bloodhound": "맹렬한 추격",
  "Quick Protection": "빠른 수호",
  "Gain 10 Gold": "10개의 골드를 얻습니다",
  "Long Strides": "긴 걸음",
  "Javelin": "투창",
  "Quick Defenses": "빠른 방어",
  "Fireflies": "반딧불이",
  "Incense": "향",
  "Kinetic Cannon": "동력포",
  "Candles": "양초",
  "Acclimation": "풍토 적응",
  "Speed Training": "속도 훈련",
  "Bjorn": "비욘",
  "Aero": "에어로",
  "Defensive Stance": "방어 자세",
  "Sword and Board": "검과 방패",
  "[DEBUG] Quest item": "텍스트 누락",
  "Monocle": "단안경",
  "Daggerwing": "단검날개",
  "Temple Reliquary": "사원 유물함",
  "Boss Harrow Rewards": "하로우 대장 보상",
  "Gain Toughness": "강인함 얻기",
  "Statia": "스타티아",
  "Healthy Tip": "건강 정보",
  "Electric Eels": "전기 뱀장어",
  "Opportunity": "기회",
  "Peacewrought": "평화의 산물",
  "Big Numbers": "큰 것들",
  "Vengeful Strike": "복수의 타격",
  "Tech Training": "테크 훈련",
  "Mantis Shrimp": "사마귀 새우",
  "Scythe": "낫",
  "Farai's Rewards": "파라이의 보상",
  "Pile of Gold 8": "골드 더미 8",
  "Nullfrost Altar": "서리무효 제단",
  "Dragon's Breath": "드래곤의 숨결",
  "Gain 5 Gold": "5개의 골드를 얻습니다",
  "Weaponsmith": "무기 대장장이",
  "Earrings": "귀걸이",
  "Epicurean Chocolate": "고급 초콜릿",
  "Inspired Brew": "영감 받은 양조",
  "Initial Chill": "초기 냉각",
  "GRN-W4SP": "녹-1벌",
  "Freiya": "프레이야",
  "Yetarian Club": "예타리아 곤봉",
  "Propeller Hat": "프로펠러 모자",
  "Investment Package": "투자 상품",
  "Pasta": "파스타",
  "Jabalian Dagger": "자발리 단검",
  "Self Portrait": "자화상",
  "Coincure": "돈치료",
  "Bill Dozer": "빌 도저",
  "Beautiful Friendship": "아름다운 우정",
  "Red Gumball": "빨간 사탕껌",
  "Restorative Risotto": "회복의 리조또",
  "Orange Piggles A": "주황 피글스 A",
  "Spyglass": "망원경",
  "Jabalian Recurve Bow": "자발리 반곡궁",
  "PvP Encounter - End of Day": "PvP 인카운터 - 하루 끝",
  "Appreciate the Moment": "순간을 소중히 여긴다",
  "Guardian's Gravy Plate": "수호자의 만찬",
  "Balcony": "발코니",
  "Welding Helmet": "용접 헬멧",
  "Furnace": "용광로",
  "Bluenanas": "블루나나",
  "Piggles Promo Pack": "피글스 프로모 팩",
  "Toxic Weapons": "유독성 무기",
  "Cybernetic Implants": "사이버네틱 이식 장치",
  "Wanted Poster": "현상수배지",
  "Bombs Away!": "폭탄 투하!",
  "Maximus": "막시무스",
  "Ritual of Alacrity": "민첩의 의식",
  "": "",
  "Healthy Jolt": "건강한 자극",
  "Bonk": "쿵",
  "The Financial District": "금융 지구",
  "Spotlight": "스포트라이트",
  "Darkstone Engine": "암석 엔진",
  "Red Piggles L": "주황 피글스 L",
  "Family Reunion": "가족 상봉",
  "Start-Up Sequence": "시동 절차",
  "Tazidian Dagger": "타지디안 단검",
  "Shrouded Figure": "수수께끼의 인물",
  "Steam Washer": "증기 세척기",
  "Vox": "복스",
  "Titan Protocol": "타이탄 프로토콜",
  "The Roughtown Kyvers Lost...": "러프타운의 카이버들이 졌습니다...",
  "Lockbox": "잠긴 상자",
  "Sands of Time": "시간의 모래",
  "Above the Clouds": "구름 위로",
  "Pop-Up Shop": "팝업 스토어",
  "Futura": "퓨투라",
  "Arbitrage": "수탈",
  "Extreme Comfort": "극한의 편안함",
  "Ambergris": "용연향",
  "Cryosleeve": "냉기 갑옷",
  "Enhance": "증강",
  "Green Piggles L": "초록 피글스 L",
  "Mothmeal": "나방가루",
  "Cannon": "대포",
  "Precision Diver": "정밀한 잠수자",
  "Improved Toxins": "향상된 독소",
  "An Ardous Journey": "힘든 여정",
  "Mad Maddie": "매드 매디",
  "Compare Big Bites": "입 크기를 비교한다",
  "Runic Double Bow": "룬 이중궁",
  "Run With It": "계속 진행한다",
  "Gold Skill": "골드 등급 스킬",
  "Aquatic Training": "수중 훈련",
  "Deadly Covenant": "치명적인 계약을 한다",
  "Engrave": "각인한다",
  "Keep it for Luck": "행운을 위해 간직한다",
  "Loan Shark": "대부업자",
  "Shield Bash": "방패 밀치기",
  "Piggles Board": "피글스 보드",
  "Banannibal": "바나니발",
  "Letter Opener": "편지칼",
  "No Upgrades Available": "강화할 수 없습니다",
  "Port": "항구",
  "Craftsmanship": "장인정신",
  "Mak": "막",
  "Obsidian Door": "흑요석 문",
  "Cash Cannon": "현금 대포",
  "Medicine Cabinet": "약 수납장",
  "Pasta Maker": "파스타 제조기",
  "[DEBUG] Nested Reference Modifier": "텍스트 누락",
  "Monitor Lizard": "모니터 도마뱀",
  "Yerdan": "예르단",
  "Alembic": "정화기",
  "Friendly Doll": "친근한 인형",
  "Dart to the Heart!": "심장을 꿰뚫어라!",
  "Get Silver Loot": "실버 등급 전리품 획득",
  "Ice Cubes": "얼음 조각",
  "Nitrogen Hammer": "질소 망치",
  "Treasure Location": "보물의 위치를 묻는다",
  "Bag of Jewels": "보석 주머니",
  "Dinosawer": "공룡톱차",
  "Circle of Life": "생명의 순환",
  "Friend Training": "친구 훈련",
  "Nanobot Blue": "나노봇 블루",
  "Open for Business": "영업 개시",
  "Crocodile Tears": "악어의 눈물",
  "Wrecking Ball": "철구",
  "Med Kit": "의료 키트",
  "Teddy": "테디",
  "Landscraper": "지상수집가",
  "Alacrity": "날쌤",
  "Standardized Toxins": "표준화 독소",
  "Pizza": "피자",
  "Honed Arsenal": "연마된 무기",
  "BazaarCON": "바자르콘",
  "Dire Inge Reward": "무시무시한 잉글릿 보상",
  "Sharpened Steel": "연마된 강철",
  "The Antiquarian": "골동품 상인",
  "Broken Shackles": "부서진 족쇄",
  "Submerged": "잠행",
  "Clear the Way": "길을 청소한다",
  "Zurphin's Safari": "저핀의 사파리",
  "Jack of All Trades": "팔방미인",
  "Blast Doors": "방폭문",
  "Medium Package": "중형 패키지",
  "A Routine Job": "일상적인 작업",
  "Wetware": "습식 갑옷",
  "Gingerbread House": "진저브레드 하우스",
  "Bet on the Game": "게임에 돈을 건다",
  "Small Weaponry": "소형 무기류",
  "Yeti Claw": "예티 발톱",
  "Prosperous Estates": "번영한 영지",
  "Diamond Heart": "다이아몬드 하트",
  "Sextant": "육분의",
  "Atlas Stone": "아틀라스 거석",
  "Fruit Press": "과일 착즙기",
  "Temple Expedition Ticket": "사원 탐험 티켓",
  "Install Off-Grid Power": "독립 전력 설치",
  "Slow Burn": "느린 불길",
  "Peaceful Eye": "평화로운 눈",
  "Growth Spurt": "성장 촉진",
  "Regenerative Tincture": "재생의 묘약",
  "Reflecting Pool": "비치는 우물",
  "Trained": "훈련된 자",
  "Sharkray": "샤크레이",
  "Time to Tinker": "땜질 시간",
  "Runic Blade": "룬 검",
  "Search the Bodies": "시체를 수색한다",
  "Rejuvenating Blend": "회복 약제",
  "Regenald": "리제널드",
  "Sergeant Suds": "서즈 하사",
  "Sauna": "사우나",
  "Flambe": "플람베",
  "Slingshot": "새총",
  "Buffed and Polished": "강화하고 광내기",
  "Ifrit's Endowment": "이프리트의 선물",
  "Sorbet": "소르베",
  "Anchor": "닻",
  "Heal Power": "회복의 힘",
  "Hatchet": "손도끼",
  "Piggles Launcher": "피글스 발사기",
  "Augment Reagents": "증강 시약",
  "Silver Merchant": "실버 등급 상인",
  "Potent Potables": "독한 시약",
  "Botanical Gardens": "식물원",
  "Transform Medium": "중형 아이템을 변환한다",
  "Thrusters": "추진기",
  "Closing Speed": "마지막 가속",
  "QA Test Monster": "QA Test Monster",
  "Shuriken": "수리검",
  "Pay Wink's Toll": "윙크의 입장료를 지불한다",
  "Sword of Swords": "검 중의 검",
  "2nd Quarter": "2쿼터",
  "Inspirational Cooking": "영감을 주는 요리",
  "Electrified Hull": "전기 충격 장갑",
  "Grease Fire": "불타는 기름",
  "Frozen Flame": "얼어붙은 화염",
  "Magnus' Femur": "매그너스의 대퇴골",
  "Thieves Guild Discount": "도둑 길드 할인",
  "VIP Pass": "VIP 패스",
  "Frost Street Champion": "서릿길 챔피언",
  "Shipwreck": "난파선",
  "Binoculars": "쌍안경",
  "First Responder": "초동 구조자",
  "Red Button": "빨간 버튼",
  "Shovel": "삽",
  "Tools of the Trade": "전문 도구",
  "Investment Pitch": "투자 제안",
  "Distributed Systems": "분산 공격 체계",
  "PiggleStorm Gaming House": "피글스톰 게이밍 하우스",
  "Emergency Shield": "긴급 방어",
  "Dragon Wing": "드래곤의 날개",
  "Double Whammy": "쌍격 망치",
  "Submersible": "잠수정",
  "Truffle Farming": "트러플 농사",
  "Bar of Gold": "금괴",
  "Joystick": "조이스틱",
  "Follow-Up Care": "후속 치료",
  "Hellbilly": "헬빌리",
  "Bomb Voyage": "폭탄 여행",
  "Turtle Shell": "거북이 등껍질",
  "Shield Amplifier": "방어 증폭기",
  "Clockwork Blades": "시계태엽 검",
  "Grabinator": "포획기",
  "Barbspike Warden": "가시송곳 수호자",
  "Stout Fire": "굳센 화염",
  "Gold or Diamond item": "골드 또는 다이아몬드 등급 아이템",
  "Pizza Cutter": "피자칼",
  "Blue Piggles R": "파랑 피글스 R",
  "Grapeshot": "포도탄",
  "Hydraulic Press": "유압 프레스",
  "Brass Knuckles": "황동 너클",
  "Core Upgrade": "코어 강화",
  "Cybersecurity": "사이버 보안요원",
  "Mimic": "미믹",
  "Idol of Decay": "부패의 우상",
  "Get Gold or Diamond Loot": "골드 또는 다이아몬드 등급 전리품 획득",
  "Caracara": "카라카라",
  "Vial of Blood": "혈액 시약병",
  "Yellow Gumball": "노란 사탕껌",
  "Chit-chat": "잡담한다",
  "Eye of the Colossus": "거신의 눈",
  "Pol": "폴",
  "Z-Sword": "Z-소드",
  "Dino Saddle": "공룡 안장",
  "Sunderer": "분쇄자",
  "Atmospheric Sampler": "공중 수집기",
  "Invest": "투자",
  "LavaRoller": "용암 롤러",
  "Final Dose": "마지막 투여",
  "Life Conduit": "생명의 도관",
  "Atomic Clock": "원자 시계",
  "Ornithopter": "퍼덕이는 날틀",
  "Makeshift Barricade": "임시 장벽",
  "Vineyard": "포도밭",
  "Hot Stones": "뜨거운 돌",
  "Keep it": "가진다",
  "Poppy Field": "양귀비 밭",
  "Silencer": "소음기",
  "Claw Arm": "집게 팔",
  "Force Field": "힘 장벽",
  "Harkuvian Launcher": "하르쿠비안 발사기",
  "Just Keep Swimming": "계속 수영합니다",
  "Oxygen Tank": "산소 탱크",
  "Glimpse of Insight": "통찰의 한조각",
  "Harkuvian Rocket Trooper": "하르쿠비안 로켓 병사",
  "Coconut": "코코넛"
};